### ISSUE TITLE
Fail to compile library with latest c++ standard

### ISSUE THREAD

**Issue by decades42** [KN4CK3R/OSHGui#19]
Error: error C3861: "obj_":  identifier not found from [here](https://github.com/KN4CK3R/OSHGui/blob/master/Misc/Any.hpp#L88). Any fix for this?

**Comment by decades42** [comment]
nvm fixed with cpp17 :)

**Comment by KN4CK3R** [comment]
That should still not work as intended. Thank you for the report.
